version: "3.3"
services:
  kube-bench:
    image: sze-k8s-audit:latest
    volumes:
      - ./bin:/root/bin
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VCS_REF
        - VCS_URL
        - VERSION
        - BUILD_DATE
        - VENDOR
        - NAME
        - DESCRIPTION
